name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Устанавливаем Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '16' # Укажите версию Node.js, которую используете
          cache: 'pnpm' # Кешируем pnpm для ускорения сборки

      # Устанавливаем pnpm через corepack
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          echo "pnpm version: $(pnpm -v)" # Проверяем, что pnpm установлен

      # Устанавливаем зависимости
      - name: Install dependencies
        run: pnpm install

      # Собираем проект
      - name: Build project
        run: pnpm build

      # Деплой на Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: medicine-catalog-20eb6
